export const GET_ROUTES_ACTION = 'GET_ROUTES';
export const SET_ROUTES_ACTION = 'SET_ROUTES';
export const UPDATE_ROUTE_LIST_ACTION = 'UPDATE_ROUTE_LIST';
export const SET_ROUTES_ERROR_ACTION = 'SET_ROUTES_ERROR';
export const ADD_ROUTE_ACTION = 'ADD_ROUTE';
export const SET_IMPORTING_ACTION = 'SET_IMPORTING';
export const ROUTES_SET_LOADING = 'ROUTES_SET_LOADING';
