export const SHARED_ROUTES_SET_ROUTES = 'SHARED_ROUTES_SET_ROUTES';
export const SHARED_ROUTES_GET_ROUTES = 'SHARED_ROUTES_GET_ROUTES';
export const SET_AD_IS_READY = 'SET_AD_IS_READY';
export const SET_AD_IS_VISIBLE = 'SET_AD_IS_VISIBLE';
